package tools.util;

public enum ArticleMetrics {
	TEXT_TERM,
	WIKI_ARTICLE,
	CYC_MAPPING,
	ARTICLE_PROB,
	ARTICLE_PROB_CONTEXT,
	WMI_RELATEDNESS,
	WMI_RELATEDNESS_FAMILY,
	WMI_RELATEDNESS_REVERSE_FAMILY,
	CYC_RELATEDNESS;
}
